# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'La Roja de Bruselas' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for La Roja de Bruselas
  pod 'Firebase'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'  

end
